---
# Sets up an Althea exit node, which proxies traffic to the internet and bills for it

- name: Install Althea exit
  hosts: exit
  user: root
  roles:
    - install-deps
    - install-babel
    - install-wireguard
    - install-rita-exit
    - setup-nat
