---

- name: Enable copr
  shell: dnf copr enable jdoss/wireguard
  become: true

- name: Install wireguard
  dnf:
    name: "{{item}}-{{wireguard_version}}"
  become: true
  allow_downgrade: true
  with_items:
    - wireguard-dkms
    - wireguard-tools
