---

- name: Download repo file
  get_url:
    url: "{{wireguard_rhel_repo}}"
    dest: /etc/yum.repos.d/wireguard.repo
  become: true

- name: Install epel
  yum:
    name: epel-release
    state: present
  become: true

- name: Install wireguard
  yum:
    name: "{{item}}-{{wireguard_version}}"
  allow_downgrade: true
  become: true 
  with_items:
    - wireguard-dkms
    - wireguard-tools
