---
- name: Copy over babled
  copy:
    src: babeld
    dest: /usr/bin/babeld
    mode: 0755
  become: true

- name: Fail on nonsystemd systems
  fail:
    msg: "No support for non systemd services, please add support for your init system!"
  when: "ansible_service_mgr != 'systemd'"

- include_tasks: systemd.yml
